// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA24ohdLKBuSYaVpAAb5zOeo-GPiI3QoOs',
    appId: '1:642773184847:web:d1ba00295f7b7d7e29d53a',
    messagingSenderId: '642773184847',
    projectId: 'tiktok-clone-4d60f',
    authDomain: 'tiktok-clone-4d60f.firebaseapp.com',
    storageBucket: 'tiktok-clone-4d60f.appspot.com',
    measurementId: 'G-CQ64GEPTEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj9_G_08v7xyKXd68LtBUTgwpfjQL-0x4',
    appId: '1:642773184847:android:02b31ab0f41adb4629d53a',
    messagingSenderId: '642773184847',
    projectId: 'tiktok-clone-4d60f',
    storageBucket: 'tiktok-clone-4d60f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhkOF6LlpS82Qp10ojzONoXxqeliX8Qro',
    appId: '1:642773184847:ios:c5deb507d155640929d53a',
    messagingSenderId: '642773184847',
    projectId: 'tiktok-clone-4d60f',
    storageBucket: 'tiktok-clone-4d60f.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhkOF6LlpS82Qp10ojzONoXxqeliX8Qro',
    appId: '1:642773184847:ios:c5deb507d155640929d53a',
    messagingSenderId: '642773184847',
    projectId: 'tiktok-clone-4d60f',
    storageBucket: 'tiktok-clone-4d60f.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA24ohdLKBuSYaVpAAb5zOeo-GPiI3QoOs',
    appId: '1:642773184847:web:22c260be9da6b6dc29d53a',
    messagingSenderId: '642773184847',
    projectId: 'tiktok-clone-4d60f',
    authDomain: 'tiktok-clone-4d60f.firebaseapp.com',
    storageBucket: 'tiktok-clone-4d60f.appspot.com',
    measurementId: 'G-DMN34Z5P2D',
  );
}
